name: Teams
version: '${project.version}'
main: net.mineando.teams.Teams
api-version: '1.13'
authors: [Mineando]
description: Un plugin de equipos para Minecraft
permissions:
  teams.admin:
    description: Permite usar comandos de administración de equipos
    default: op
