name: Build and Release
on:
  push:
    branches:
      - main
      - beta
      - alpha
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
        contents: write
        packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Install Semantic Release
        run: npm install -g semantic-release

      - name: Install Semantic Release modules
        run: npm install @semantic-release/changelog @semantic-release/git @semantic-release/github @semantic-release/exec gradle-semantic-release-plugin

      - name: Grant execute permission for update-versions.sh
        run: chmod +x update-versions.sh

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release